
2023-06-19 23:39:33,583 ERROR Internal Server Error: /news/ D:\GIT\Projects\SkillFactory\News Portal\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('news/post_list.html'), <traceback object at 0x000001A2D0FD3680>)
Traceback (most recent call last):
  File "D:\GIT\Projects\SkillFactory\News Portal\venv\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GIT\Projects\SkillFactory\News Portal\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\GIT\Projects\SkillFactory\News Portal\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GIT\Projects\SkillFactory\News Portal\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GIT\Projects\SkillFactory\News Portal\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GIT\Projects\SkillFactory\News Portal\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
2023-06-19 23:39:33,586 ERROR "GET /news/ HTTP/1.1" 500 90186 D:\GIT\Projects\SkillFactory\News Portal\venv\Lib\site-packages\django\core\servers\basehttp.py None
